export const SET_STRIPE = 'SET_STRIPE'
export const CREATE_STRIPE_SOURCE = 'CREATE_STRIPE_SOURCE'
export const SET_STRIPE_ERROR = 'SET_STRIPE_ERROR'
export const CLEAR_STRIPE_ERROR = 'CLEAR_STRIPE_ERRROR'
