export const FETCHING_OBJECTS_REQUESTED = 'FETCHING_OBJECTS_REQUESTED'
export const FETCHING_OBJECTS_SUCCESS = 'FETCHING_OBJECTS_SUCCESS'
export const FETCHING_OBJECTS_FAILURE = 'FETCHING_OBJECTS_FAILURE'

export const CREATION_OBJECT_FAILURE = 'CREATION_OBJECT_FAILURE'
export const CREATION_OBJECT_REQUESTED = 'CREATION_OBJECT_REQUESTED'
export const CREATION_OBJECT_SUCCESS = 'CREATION_OBJECT_SUCCESS'

export const UPDATE_OBJECT_FAILURE = 'UPDATE_OBJECT_FAILURE'
export const UPDATE_OBJECT_REQUESTED = 'UPDATE_OBJECT_REQUESTED'
export const UPDATE_OBJECT_SUCCESS = 'UPDATE_OBJECT_SUCCESS'
