export const FETCHING_OBJECTS_REQUESTED = 'FETCHING_OBJECTS_REQUESTED'
export const FETCHING_OBJECTS_SUCCESS = 'FETCHING_OBJECTS_SUCCESS'
export const FETCHING_OBJECTS_FAILURE = 'FETCHING_OBJECTS_FAILURE'
