export const FETCHING_ECOSYSTEMS_REQUESTED = 'FETCHING_ECOSYSTEMS_REQUESTED'
export const FETCHING_ECOSYSTEMS_SUCCESS = 'FETCHING_ECOSYSTEMS_SUCCESS'
export const FETCHING_ECOSYSTEMS_FAILURE = 'FETCHING_ECOSYSTEMS_FAILURE'

export const CREATE_ECOSYSTEM_REQUESTED = 'CREATE_ECOSYSTEM_REQUESTED'
export const CREATE_ECOSYSTEM_SUCCESS = 'CREATE_ECOSYSTEM_SUCCESS'
export const CREATE_ECOSYSTEM_FAILURE = 'CREATE_ECOSYSTEM_FAILURE'

export const SET_CURRENT_ECOSYSTEM = 'SET_CURRENT_ECOSYSTEM'

export const APPEND_NEW_SERVICE = 'APPEND_NEW_SERVICE'

export const LOAD_ECOSYSTEM_REQUESTED = 'LOAD_ECOSYSTEM_REQUESTED'
export const LOAD_ECOSYSTEM_SUCCESS = 'LOAD_ECOSYSTEM_SUCCESS'

export const CREATE_ECOSYSTEM_GROUP_REQUESTED =
	'CREATE_ECOSYSTEM_GROUP_REQUESTED'
export const CREATE_ECOSYSTEM_GROUP_SUCCESS = 'CREATE_ECOSYSTEM_GROUP_SUCCESS'
export const CREATE_ECOSYSTEM_GROUP_FAILURE = 'CREATE_ECOSYSTEM_GROUP_FAILURE'
