export const FETCHING_ECOSYSTEMS_REQUESTED = 'FETCHING_ECOSYSTEMS_REQUESTED'
export const FETCHING_ECOSYSTEMS_SUCCESS = 'FETCHING_ECOSYSTEMS_SUCCESS'
export const FETCHING_ECOSYSTEMS_FAILURE = 'FETCHING_ECOSYSTEMS_FAILURE'
export const SET_CURRENT_ECOSYSTEM = 'SET_CURRENT_ECOSYSTEM'

export const APPEND_NEW_SERVICE = 'APPEND_NEW_SERVICE'
